name:                bedkom-api
version:             0.1.0.0
github:              "https://github.com/JonasTriki/bedkom-api"
license:             GPL-3
author:              "Jonas Triki"
maintainer:          "jonas@triki.no"
copyright:           "2019 Jonas Triki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JonasTriki/bedkom-api#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- aeson
- servant-server
- wai
- warp
- http-client
- ini
- text
- wreq
- tagsoup
- scalpel-core
- regex-tdfa
- html-entities
- bytestring
- containers
- uri-bytestring

library:
  source-dirs:
    - src
    - src/utils

executables:
  bedkom-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bedkom-api

tests:
  bedkom-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bedkom-api
