app: bedkom
tenant: triki
service: bedkom-api

provider:
  name: aws
  profile: default
  runtime: nodejs8.10

  stage: ${opt:stage, 'dev'}
  region: eu-central-1

plugins:
  - serverless-offline

functions:
  app:
    handler: main.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      NODE_ENV: ${self:provider.stage}